### ISSUE TITLE
Ordering variables incorreclty

### ISSUE THREAD

**Issue by madeleineostoja** [willofindie/vscode-cssvar#10] opened 2021-09-10 09:49 UTC
Thanks for the excellent extension! I've added it to the official recommendation for my CSS library, [Pollen](https://www.pollen.style) 🙂

Just a minor issue I noticed, the variable ordering/alphabetising in the autocomplete popup is incorrect when it comes to numbers. Eg:

<img width="138" alt="Screen Shot 2021-09-10 at 9 47 32 PM" src="https://user-images.githubusercontent.com/6374876/132835414-fdbfcbcc-c91b-49dd-a18e-58c4aa643791.png">

**Comment by phoenisx** [comment] 2021-09-10 12:30
Thanks for the support @madeleineostoja. Really appreciate it 🙇🏾‍♂️ 

Anyways, the plugin doesn't have sorting present yet. Will add this feature in the `v0.1.1` release.

**Comment by phoenisx** [comment] 2021-09-10 13:51
## RFC

@madeleineostoja What I am not able to understand from your issue is that, how do you want to sort the property names??

I can add a sorting mechanism that will sort property name alphabetically, but it will still not solve your issue, for e.g. `["size-2", "size-12"]`, will get sorted to `[ "size-12", "size-2" ]`, which I don't think is what you desire.

Also, having a custom sort mechanism would not be a good idea, because how users will use this plugin is not defined!!
For e.g. they might have a naming convention that has two sets of numbers, like `pad-2-4`, `pad-12-24`.

**_What I am trying to say is it's not defined on what part of the string I need to apply the custom sort._**

I can think of a solution, which adds a vscode config, where users can pass an object with regex and a single [Capture Group](https://javascript.info/regexp-groups) with a type I need to sort with.:

```js
{
  "sort": {
    pattern: "\w*(\d+)",  // Get the first set of numbers, and sort with the captured string
    type: "number", // This can be a number or a string
  }
}
```

But again above solution feels too complicated and might be confusing for people to use, without proper examples.

Anyways, I am open to suggestions here!

**Comment by madeleineostoja** [comment] 2021-09-10 23:48
Oh strange! I guess VS Code is doing its own sorting of the suggestions. I’d just leave it at that then, if it’s a vs code issue not a plug-in issue

**Comment by phoenisx** [comment] 2021-09-11 11:25
Hi @madeleineostoja 

I have added support for unstable features, which will be used to support some unconventional requirements in this plugin.
I have added support for the `no_sort` feature, which will be released as part of `v0.1.1`, which if enabled will disable the VSCode's default sort for cssvar plugin.

Though this might have side effects. For e.g. if you are using multiple files for CSS variable sorting will depend on which file will be opened first and so on.

Anyways you can try the feature out, and let me know your thoughts!


## Screenshots

<img width="229" alt="image" src="https://user-images.githubusercontent.com/11786283/132945806-b43df1d8-d4f0-4682-abf3-79152af51cba.png">

**Closed** 2021-09-11 11:29 UTC

**Comment by phoenisx** [comment] 2021-10-17 06:30
Hi @madeleineostoja 

It's good to hear from you.

I completely understand your concern, but I feel keeping this feature enabled by default will break VSCode's default sorting, which in my opinion would be an unexpected behavior for many users. That's the reason I kept this feature behind a flag and not in-built.

I will keep an eye on this issue, and if more users have the same concern, I will remove the flag to make this behavior default. 👍🏼

**Comment by madeleineostoja** [comment] 2021-10-17 07:58
Makes sense! Is there a reason why it’s behind “unstable” flags?
