### ISSUE TITLE
The extension stopped working again

### ISSUE THREAD

**Issue by SineYlo** [willofindie/vscode-cssvar#36] opened 2022-05-20 10:14 UTC
This extension will soon make me hysterical :)
Then everything worked, but now I have deployed a larger project and everything has apparently broken…
Did everything exactly the same as then, but it still issues a warning:
![picture-1](https://i.ibb.co/pZsvWb5/9dfej5-M1o-N.png)

Here are my settings in the global file — `setting.json`
![picture-2](https://i.ibb.co/m0Hw12V/Code-O54-Isv-Vn-UT.png)

I also attach screenshots from the `package.json` file and `node_modules` folder with proof that I have installed the necessary packages:
![Code_lqVMx89GT6](https://user-images.githubusercontent.com/56423781/169506260-e22c6156-d2b7-4771-b4e2-f255b926b682.png)
![Code_XygbnWHf38](https://user-images.githubusercontent.com/56423781/169506279-875a77c6-a67a-47c5-a3d8-3779d1ebe5a8.png)

The funny thing is that everything works well with CSS files, but as soon as I move into a project where variables are written in SCSS files, everything immediately stops working and knocks out a warning, which is shown in the very first screenshot.
Running VS Code as an administrator didn't solve the problem either.
Maybe I forgot to do something, but that's just not clear to me yet. Either, I did everything right, and it's already about expansion.

**Comment by phoenisx** [comment] 2022-05-21 18:56
You need to define `"cssvar.postcssSyntax": ["postcss-scss"]` property as well, as defined [here](https://github.com/willofindie/vscode-cssvar/blob/master/customize-extension.md#adding-support-for-any-new-sytax).

_In future, I will possibly remove this property from the config and auto-configure it, but for now you need to define `cssvar.postcssSyntax` property._

If it still does not work, can you share the content of the SCSS file (filename is displayed in the warning popup that you get)?

**Comment by SineYlo** [comment] 2022-05-22 00:50
Well, in general, the warning has disappeared, but now another error has appeared
![image](https://user-images.githubusercontent.com/56423781/169673648-49e3bfae-13a4-4770-8846-49787d4d7a70.png)

That's how I now have it written in global `settings.json`
![image](https://user-images.githubusercontent.com/56423781/169673671-1e7770a4-248a-494c-b2ae-894533bfc9e5.png)

Here is the full screenshot where I showed that I installed the packages in `devDependencies`
![image](https://user-images.githubusercontent.com/56423781/169673714-13d3d0eb-2d14-4043-8cf4-87167e97d582.png)

I tried to install these packages simply in `dependencies`, but this did not solve the problem. I also tried to install the `postcss-scss` package globally, and it didn't really help either.

**Comment by phoenisx** [comment] 2022-05-22 17:58
I am not able to replicate your issue, can you please share an isolated repro of this issue?

I have one suggestion though, can you move your global `cssvar` settings to local `.vscode/settings.json` and try if it works?

**Comment by SineYlo** [comment] 2022-05-23 02:02
I tried to transfer it to the local config and still the exact same red error…
If there is a desire to understand the problem, then I attach the repository in which I tried to do all this
https://github.com/SineYlo/sit-down-pls
The variables are located in the folder - `src/scss/config/variables/`

**Comment by phoenisx** [comment] 2022-05-24 09:20
It works for me, as is, no changes made to your project
![recording](https://user-images.githubusercontent.com/11786283/169996444-a6718462-e50d-4e94-8534-c5930d43caab.gif)

---

Can you share which VSCode version are you using, though I am not sure if it's due to any of the VSCode APIs.
Also once you change the `cssvar` config/settings or re-install `postcss-scss` module in local, did you try restarting VSCode or refreshing the Window (`CMD+SHIFT+P -> Developer: Reload Window`)?

I should start adding logs to prod builds. Will do it in a separate release 👍🏾

**Comment by phoenisx** [comment] 2022-05-24 09:25
Can you uninstall `postcss` and `postcss-scss` from global `node_modules` if it was installed globally earlier?
I guess it might be messing with NodeJS's `require.resolve` API.

**Comment by SineYlo** [comment] 2022-05-25 01:13
In general, I tried everything in short, probably everything that is possible and impossible, but in the end nothing happened…
But there is one interesting point that I identified during the tests.
There is such a program called `Prepros` (you may have heard of it).
So the most interesting thing is if you run it in the project, the variables start working, but the error still does not go anywhere.
It is possible that the program itself somehow configures `PostCSS` and thereby the variables become visible.
Of course, you can run this program in projects every time, but this is not the solution to the problem.
In addition, the error still remains even though the variables work…
Yesterday I asked a friend to install this extension and for him to check whether it works for him or not, which is funny, it doesn't work either (it gives exactly the same error) :).
He also has MacOS, just like you. I have Windows and I thought that the issue was because of this, but as it turned out, no.
I also tried to install `postcss` and `postcss-scss` globally on the computer today, and it doesn't work either.
And I also forgot to say that in the config of the `Prepros` program, there is a mention of the packages — `postcss-import` and `postcss-preset-env`.
Perhaps because of them, even taking into account the error, it all works, but this is not accurate.
Also, I think it is not necessary to create a local `settings.json` file, because, again, nothing has changed much for me.

---

Here are the versions of my programs, maybe it will help somehow:

-  VS Code - 1.67.2
- Node.js - 16.15.0 (yesterday there was version `16.13.0`, but I reinstalled it to `16.15.0`, but it didn't help much)
- npm - 8.5.5

---

I'm ready to sell my soul to the devil if only this extension would work… :D

**Comment by SineYlo** [comment] 2022-05-25 21:39
I had an idea to reinstall VS Code, but I'm not sure it will help.

**Comment by phoenisx** [comment] 2022-05-30 05:38
Thanks @SineYlo 

Even I feel this could be due to some other Extension that you are using.
Do let me know if re-installing VSCode helps.

If it works, try re-installing extensions one at a time, which would help you to narrow down the extensions which conflict with `cssvar` extension.

**Comment by SineYlo** [comment] 2022-05-31 05:56
I completely reinstalled VS Code, but it didn't solve the problem…
Then what is the problem at all is unclear.

**Comment by SineYlo** [comment] 2022-06-04 09:50
Is it possible that it's all about the extension itself?
I tried to install a similar extension — `vunguyentuan.vscode-css-variables` and it worked for me.
Yes, it also works with jambs, but still.
I'm just curious to figure out what the problem is… 😇

**Comment by phoenisx** [comment] 2022-06-08 02:55
Apologies for the delay, I am away and couldn't take a look.

I will try to replicate with the Node/VSCode versions you mentioned, once I am back.
I will keep this issue open until I find the error, though I cannot assure you when will I be able to fix the issue.

I feel it would be great to release a version which adds these errors to VSCode devtools log, so that you can forward me the error log 👍🏾 
This I can immediately publish when I am back and will update here.

Apologies for the inconvenience caused by this extension, feel free to switch to `vunguyentuan.vscode-css-variables` in the meantime.

**Comment by phoenisx** [comment] 2022-07-16 10:50
Hi @SineYlo 

I have added a custom logger to log out errors when this extension fails to parse some files.
Can you gather the info from your VSCode Devtools, whenever possible and share it on this thread?

The error log contains the line/column number of a file where the parser failed. You can share the details from the source for that line/column number, for me to investigate further 👍🏾

**Comment by SineYlo** [comment] 2022-07-18 05:33
Hi @phoenisx 
Is there an instruction on how to do it all?
Because I haven't done this before and, to be honest, I can't imagine how it can be done

**Comment by phoenisx** [comment] 2022-07-18 07:13
Hey @SineYlo 

I wrote a doc on this [here](https://github.com/willofindie/vscode-cssvar/blob/main/debug-extension.md).

Let me know if that helps to debug the error for you.

**Comment by SineYlo** [comment] 2022-07-18 08:04
I don't even have a log displayed for some reason…
![image](https://user-images.githubusercontent.com/56423781/179468941-a0e960f4-9616-4bcd-9e25-9460feff7cb3.png)

It just shows the same error that pops up from the bottom right of the screen

**Comment by phoenisx** [comment] 2022-07-18 09:37
Let's park this for now.

I feel your node is somehow unable to resolve the `postcss-scss` module. Not sure why!! 🤔 

I am pretty sure if you run `require.resolve('postcss-scss')` in your `node` REPL, from your project's directory, you will be getting an error.

i.e., we can try this one last thing:

- Force Install (remove and re-install) `postcss-scss` locally in your project
- Run `node` REPL
- Run `require.resolve('postcss-scss')`

If you get an error, then it's for sure you have set up your nodejs incorrectly.

If not, no worries!!

I appreciate your patience and sticking to the issue to help me figure out the cause.
Apologies we couldn't find any fix 🙇🏾 

I am working on v2.0 (to create a simple generic parser) which will remove the hassle of installing separate syntax/parser modules locally to make the extension work.

Let me know if you are able to make this work.
I will be closing this issue now since we are not able to reach any conclusion,
and the extension is working for me 👍🏾

**Comment by SineYlo** [comment] 2022-07-18 09:58
The terminal did not issue an error when executing the command
![image](https://user-images.githubusercontent.com/56423781/179488082-9e704c9e-7d81-4490-8d24-d6df7977a1c7.png)

It turns out that the problem is not on my side?
Anyway, I will wait for version 2.0 😇

**Comment by phoenisx** [comment] 2022-07-18 11:54
Can you try one last thing for me??

Can you give me the output for the following:

```
require(require.resolve('postcss-scss'));
```

**Comment by phoenisx** [comment] 2022-07-18 12:11
Thanks for your quick response!! 🙇🏾 

Can you try the following as well:

```
require(require.resolve("postcss-scss", { paths: [] }));

require(require.resolve("postcss-scss", { paths: undefined }));
```

**Comment by SineYlo** [comment] 2022-07-18 12:16
The first result:
![image](https://user-images.githubusercontent.com/56423781/179509055-f76963fd-771e-4a55-859b-57ce26963148.png)

The second result:
![image](https://user-images.githubusercontent.com/56423781/179509171-f7e5542b-dde1-4315-a414-329b06921cb9.png)

**Comment by phoenisx** [comment] 2022-07-18 12:21
I think somehow the VSCode API is not returning values for workspace folders on your system, which could be the cause of the error.
I am not entirely sure, but it's a possibility.

Let me release a patch fix for this, and you can try once with that version. If that fixes the issue, great, else I am not sure. Probably wait for v2 😅

**Comment by SineYlo** [comment] 2022-07-18 12:25
Okay, if it's not too much trouble, let me know when the fix comes out

**Comment by phoenisx** [comment] 2022-07-18 13:04
Hey @SineYlo 

Can you try v1.4.3, and verify if that works for you?

**Comment by SineYlo** [comment] 2022-07-19 03:26
Hi @phoenisx 
In general, this did not solve the problem…
I even deleted `NVM` and `Node`, then reinstalled the usual `Node` version `14.20.0` again
And that didn't solve the problem either :)
But!
I tried to open `VS Code DevTools` again and saw the following there:
![image](https://user-images.githubusercontent.com/56423781/179657106-fbcc179c-a79b-469b-b9c5-58c4965c49f6.png)
Maybe this will help somehow 😇
Perhaps he lacks some files or something else to run the extension
And another funny moment
Autocompletion of variables started working for some reason :D
But everything else still doesn't work
Perhaps this is some kind of bug, or we are on the way to the truth 🙂

**Comment by phoenisx** [comment] 2022-07-19 03:53
I think your autocompletion is working because the SCSS files that you are using to test this bug, do not have crazy SASS syntax, and the parser does not fail, as the default parser kicks in if no other parser is provided.

The error is clear, `postcss-scss` parser is not found. Why? I am not sure.


Let's park this. I will try to release v2 asap.
Thanks for your support @SineYlo 💯

**Closed by phoenisx** 2022-07-19 03:53 UTC

**Comment by phoenisx** [comment] 2022-07-19 04:13
@SineYlo If you can look into this issue yourself, as I feel this is very specific to your system, and the way VSCode is set up, it would be helpful.

You can clone this repo, and `yarn install` the modules, and to run the extension locally, you need to open this on VSCode and launch the extension using `F5` (I guess it's the same on Windows) in debug mode.
This will open a new VSCode window, where you can open this broken project and `console.log` the value of [this code](https://github.com/willofindie/vscode-cssvar/blob/main/src/parser.ts#L32).

I think the value of `folder.uri.path` is coming wrong somehow in your system, or it should be set to `folder.uri.fsPath` instead. Not sure about this API, even I am learning 😅

**Comment by phoenisx** [comment] 2022-07-19 04:23
I think I got the issue, and it's happening due to Windows, as mentioned in the VSCode source code comment here:

```
The *difference* to the [`path`](#Uri.path)-property is the use of the platform specific
path separator and the handling of UNC paths. The sample below outlines the difference:
```

So, I think using `fsPath` instead of `path` should fix your issue, as it provides platform specific paths.

Man, this issue is going on forever 😓 
I have work to do today, will commit a fix by today EOD.
The problem is I am not able to test it on Windows.

**Comment by phoenisx** [comment] 2022-07-19 04:24
I didn't think it was platform specific, because you said it failed for one of your friends as well, who was using macOS.

Anyways I will give it a try, better than doing nothing 😄

**Comment by SineYlo** [comment] 2022-07-19 06:52
Today I will try to sort out this problem again 🤓
As soon as you release the update, let me know
I hope this will help solve the problem
I'll come home, try to clone the repository and change the `path` value to `fsPath`
There's nothing to do for now anyway, but if it doesn't work out, it will be clear what's what :D

**Comment by SineYlo** [comment] 2022-07-19 10:19
I managed to solve the problem!!!!!!!!!!! 🤩
In general, yes, if you replace `path` with `fsPath`, then the error does not appear
The trick is that in Windows OS, a backslash is used in the paths — `\`, most likely this was the cause of the problem
I think it's not for nothing that all this happened because now you will know that on Windows, paths are written a little differently 😇

**Comment by phoenisx** [comment] 2022-07-19 15:47
I've released `v1.4.4`. Do test it out!!!

🤞🏾 It should be working now 😅

**Comment by SineYlo** [comment] 2022-07-19 22:23
Now there is no error and everything works fine 😌
But!
There is another interesting point

The following error is displayed in VS Code DevTools
![image](https://user-images.githubusercontent.com/56423781/179857745-0838e4b9-17da-4acc-a07a-aab706bc7629.png)
When I started the extension locally, this error was also displayed in the VS Code console
Maybe this is also somehow related to Windows

**Comment by SineYlo** [comment] 2022-07-19 22:26
I found some solution on `SO` you can try it
https://stackoverflow.com/questions/50432238/tracing-a-deprecation-warning

**Comment by phoenisx** [comment] 2022-07-20 02:18
I have seen that error. It’s not related to this plugin

> Now there is no error and everything works fine

That sounds great. Thanks for your patience and support 🙇‍♂️
